### ISSUE TITLE
关于新手指南的简体中文翻译

### ISSUE THREAD

**Issue by cdluminate** [debiancn/debmake-doc#1]
看上去这是一个正在翻译中的新手指南。

虽然现存有一个相对完整的新手指南[1]，不过根据Osamu，maint-guide的英文原版早就不再大改了，只是有一些翻译上的修复。而新版的新手指南就是Osamu的这个debmake。maint-guide简体中文版虽然有，但是这个中文翻译是有一些问题的，但我有一直忙得没时间重新修一遍翻译。

如果你的翻译工作有参考上述翻译的话，请在遇到诡异翻译时at我 :-)

另外，maint-guide的源码里边貌似有一个简体转繁体的辅助脚本，如果你想要照顾繁体中文翻译的话，或许会有一点点用处。毕竟在我之前的翻译工作中，繁体中文也是经常断更。。。

[1] https://www.debian.org/doc/manuals/maint-guide/index.zh-cn.html

**Comment by hosiet** [comment]
感谢关注！maint-guide 我也考虑过修订的问题，不过没有 ddp 项目的权限，申请加入的请求也坑着，所以先着手进行 collab-maint 上 debmake-doc 的翻译了。这里的工作只是镜像，翻译主要发生在 Alioth 的[对应 Git 仓库中](https://anonscm.debian.org/git/collab-maint/debmake-doc.git)。）

简繁转换我现在更倾向于使用[opencc](https://github.com/BYVoid/OpenCC) 1.x完成，这个比辅助脚本会好一些（我在[manpages-zh](https://github.com/man-pages-zh/manpages-zh)项目中已经切换为使用opencc了）。

现在上游还没有任何提供翻译版的意图（因为翻译工作刚刚开始），我现在的想法是等至少完成一门语言的翻译工作后再考虑发布以及中文的转换相关工作。

**Comment by cdluminate** [comment]
如果需要的话我很乐意帮你往ddp里提交commit。
一个可行的工作流程是给maint-guide submit一个bug，附带git-format-patch，顺带cc我即可。

**Comment by hosiet** [comment]
非常感谢。个人精力有限，不太确定什么时候会看看 maint-guide 的情况，但需要的时候会麻烦你帮忙进行提交的。

**Comment by hosiet** [comment]
现在我已经加入了 ddp 组，而且在 debmake-doc 和 maint-guide 上都有一定的提交。

**Comment by cdluminate** [comment]
Ack.
